const COMMENT_LENGTH = 140;
const HASH_TAG_REGULAR_EXPRESSION = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;
const INITIAL_COMMENTS_NUMBER = 5;
const DEFAULT_SCALE_AMOUNT = 100;
const MIN_SCALE_AMOUNT = 25;
const MAX_SCALE_AMOUNT = 100;
const ALERT_SHOW_TIME = 5000;
const RANDOM_PHOTOS_COUNT = 10;

export {
  COMMENT_LENGTH,
  HASH_TAG_REGULAR_EXPRESSION,
  INITIAL_COMMENTS_NUMBER,
  DEFAULT_SCALE_AMOUNT,
  MIN_SCALE_AMOUNT,
  MAX_SCALE_AMOUNT,
  ALERT_SHOW_TIME,
  RANDOM_PHOTOS_COUNT
};
